plum_new/src/Entity/Infoitem.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InfoitemRepository")
 */
class Infoitem
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Section;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Text;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSection(): ?int
    {
        return $this->Section;
    }

    public function setSection(int $Section): self
    {
        $this->Section = $Section;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->Text;
    }

    public function setText(?string $Text): self
    {
        $this->Text = $Text;

        return $this;
    }
}

plum_new/src/Form/InfoType.php
<?php

namespace App\Form;

use App\Entity\Infoitem;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InfoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Section')
            ->add('Text')
            ->add('save',SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Infoitem::class,
        ]);
    }
}

plum_new/src/Controller/InfoController.php
<?php

namespace App\Controller;

use App\Entity\Infoitem;
use App\Form\InfoType;
use App\Repository\InfoitemRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/info", name="info")
 */
class InfoController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @param InfoitemRepository $repository
     * @return Response
     */
    public function index(InfoitemRepository $repository)
    {
        $items = $repository->findAll();

        return $this->render('info/index.html.twig', [
            'infoitems' => $items,
        ]);
    }
    /**
     * @Route("/create", name="create")
     */
    public function create(Request $request) {
        $info = new Infoitem();
        $form = $this->createForm(InfoType::class, $info);

        $form->handleRequest($request);

        if($form->isSubmitted()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($info);
            $em->flush();
            return $this->redirect($this->generateUrl('infoindex'));
        }


        return $this->render('info/create.html.twig',[
            'form' => $form->createView()
        ]);
;    }

    /**
     * @Route("/show/{id}", name="show")
     * @param Infoitem $infoitem
     * @return Response
     */
    public function show(Infoitem $infoitem) {

        return $this->render('info/show.html.twig',[
            'infoitem' => $infoitem
        ]);
    }
    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function remove(Infoitem $infoitem) {
        $em = $this->getDoctrine()->getManager();
        $em->remove($infoitem);
        $em->flush();
        $this->addFlash('success', 'Item has been removed!');
        return $this->redirect($this->generateUrl('infoindex'));

    }



}

plum_new/templates/info/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info Control{% endblock %}

{% block body %}

    {{ form(form) }}

{% endblock %}

plum_new/templates/info/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info Control{% endblock %}

{% block body %}

    <h1>List of info items:</h1>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <td>ID</td>
            <td>Section</td>
            <td>Text</td>
            <td>Actions</td>
        </tr>
        </thead>
        <tbody>
            {% for i in infoitems %}
                <tr>
                    <td>{{ i.id }}</td>
                    <td>{{ i.section }}</td>
                    <td>{{ i.text}}</td>
                    <td>
                        <a href="{{  path('infoshow', {id: i.id}) }}">
                            SHOW
                        </a>
                        |
                        <a href="{{  path('infodelete', {id: i.id}) }}">
                            DELETE
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

plum_new/templates/info/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Info Control{% endblock %}

{% block body %}

    <h1>Showing item</h1>

{% endblock %}